blog1/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = "blog1"

urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.Postlistview.as_view(), name="post_list"),
    # path('posts/<int:id>', views.post_detail, name="post_detail")
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login/', auth_views.LoginView.as_view(), name="login"),
    path('login-user/', views.login_user, name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout-user/', views.logout_user, name="logout"),
    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(success_url='/blog1/password-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('register/', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
]

djangoproject22/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog1/', include('blog1.urls', namespace="blog1"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog1/forms.py
from django import forms
import re
from .models import Comment, Post, User, Account


# form ticket
class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش')
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("Enter the correct contact number")
            else:
                return phone

    def clean_email(self):
        email = self.cleaned_data['phone']
        if email:
            if not re.match(r"^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$", email):
                raise forms.ValidationError("The entered value is not a valid email")
        return email


# form comment
class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("The entered name is shorter than allowed")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'message']


# form post
class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')
    title = forms.CharField(max_length=50, label='عنوان پست')
    description = forms.CharField(widget=forms.Textarea, label='توضیحات پست')
    author = forms.CharField(max_length=50, label='نام نویسنده')

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']


class SearchForm(forms.Form):
    query = forms.CharField()


# form login
class LoginForm(forms.Form):
    username = forms.CharField(max_length=50, required=True)
    password = forms.CharField(max_length=100, required=True, widget=forms.PasswordInput)


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(max_length=30, widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(max_length=30, widget=forms.PasswordInput, label='Password2')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسوردها باهم مطابقت ندارن')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']


class LogoutForm(forms.Form):
    confirm_logout = forms.BooleanField(label='logout', required=True)

blog1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from .forms import *
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    return render(request, "blog1/index.html")


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 1)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog1/list.html", context)


# post list

# class Postlistview(ListView):
#     queryset = Post.published.all()
#     context_object_name = "post"
#     paginate_by = 3
#     template_name = 'blog1/list.html'


# post detail
@login_required
def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comment': comments
    }
    return render(request, "blog1/detail.html", context)


# class PostDetailView(DetailView):
#     model = Post
#     template_name = "blog1/detail.html"


# ticket
@login_required
def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket_obj = Ticket.objects.create()
            cd = form.cleaned_data
            ticket_obj.message = cd['message']
            ticket_obj.name = cd['name']
            ticket_obj.email = cd['email']
            ticket_obj.phone = cd['phone']
            ticket_obj.subject = cd['subject']
            ticket_obj.save()
            return redirect("blog1:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})


# comment post
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)


# create post
@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_field=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_field=form.cleaned_data['image2'], post=post)
            return redirect('blog1:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create_post.html', {'form': form})


# search post
@login_required
def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(
                similarity__gt=0.1).order_by('-similarity')
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).filter(
                similarity__gt=0.1).order_by('-similarity')
            results = (results1 | results2)
    context = {
        'query': query,
        'results': results
    }

    return render(request, 'blog1/search.html', context)


# profile user
@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    return render(request, 'blog1/profile.html', {'posts': posts})


# delete post
@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog1:profile')
    return render(request, 'forms/delete-post.html', {'post': post})


# delete image
@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog1:profile')


# edit post
@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_field=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_field=form.cleaned_data['image2'], post=post)
            return redirect('blog1:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create_post.html', {'form': form, 'post': post})


def login_user(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'blog1/profile.html', {'form': form})
                else:
                    return HttpResponse('your not login')
            else:
                return HttpResponse('you are not logged in')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


# def logout(request):
#     logout(request)
#     return redirect(request.META.get('HTTP_REFERER'))


def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})


@login_required
def edit_account(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)
    context = {
        'user_form': user_form,
        'account_form': account_form
    }

    return render(request, 'registration/edit_account.html', context)


def logout_user(request):
    if request.method == 'POST':
        form = LogoutForm(request.POST)
        if form.is_valid():
            return render(request, 'registration/logged_out.html')
    else:
        form = LogoutForm()
    return render(request, 'registration/logged_out.html', {'form': form})


def post_view(request):
    user_posts = Post.objects.filter(user=request.user)
    paginator = Paginator(user_posts, 3)
    page = request.GET.get('page')
    user_posts = paginator.get_page(page)
    return render(request, 'partilas/paginator.html', {'user_posts': user_posts})

blog1/templates/blog1/detail.html
{% extends 'parent/basa.html' %}
{% load jformat %}
{% load blog1_tags %}
{% block title %}post detail{% endblock %}
{% block content %}
    <h1>post detail (by {{ post.author }} </h1>
    <h2>post.title</h2>
    <p>{{ post.description | markdown }}</p>
    <hr>
    <p>{{ post.publish }}</p>
    <hr>
    <div>
        {% for img in post.images.all %}
            <img width="400" height="200" src="{{ img.image_field.url }}.url }}" alt="{{ img.title }}">
        {% endfor %}

    </div>
    <div>
    {% with comments.count as cm_count %}
    {{ cm_count }} comment {{ cm_count|pluralize }}
    </div>

    <div>
    {% for cm in comment %}
        {{ cm.message | linebreaks }}
        <br>
        {{ cm.name }}
    {% empty %}
        کامنتی وجود ندارد
    {% endfor %}
    {% endwith %}
    </div>
    <form method="post" action="{% url 'blog1:post_comment' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="افزودن کامنت">
    </form>
{% endblock %}

blog1/templates/blog1/index.html
{% extends 'parent/basa.html' %}
{% load blog1_tags %}
{% block title %}post list{% endblock %}
{% block content %}
    <h2>آمار</h2>
    <p>teadad posts: {% total_posts %} </p>
    <p>teadad comment: {% total_comments %}</p>
    <p>tarikh akharin post: {% last_post_data %}</p>

    {% ltest_post 5 %}

    <h2>محبوب ترین پست ها</h2>
    {% most_popular_posts as pop_posts %}
    {% for post in pop_posts %}
        <br>
        <a href="{{ post.get_absolute_url }}">{{ post.title }} : with {{ post.comment_count }} comments</a>
    {% endfor %}
{% endblock %}

blog1/templates/blog1/list.html
{% extends 'parent/basa.html' %}
{% load blog1_tags %}
{% block title %}post list{% endblock %}
{% load static %}
{% load blog1_tags %}
{% load jformat %}

{% block head %}    {% endblock %}


{% block content %}

<!-- Preloader START -->
	<div class="preloader">
		<div class="loader">
			<div class="sh1"></div>
			<div class="sh2"></div>
		</div>
	</div>
<!-- Preloader END -->

<main>

<section class="pt-4">
	<div class="container">
		<div class="row">
      <div class="col-12">
				<div class="border p-4 text-center rounded-3">
                    {% if category %}
                        <h1><a href="{% url 'blog1:post_list' %}" > لیست پست های {{ category }}</a></h1>
                    {% else %}
                        <h1><a href="{% url 'blog1:post_list' %}" >لیست پست ها</a></h1>
                    {% endif %}
					<nav class="d-flex justify-content-center" aria-label="breadcrumb">
					</nav>
				</div>
      </div>
    </div>
	</div>
</section>

<section class="position-relative pt-0">
	<div class="container" data-sticky-container>
		<div class="row">
			<!-- Main Post START -->
			<div class="col-lg-9">
				<!-- Card item START -->
                {% for post in posts %}
				<div class="card mb-4">
					<div class="row">
						<div class="col-md-5">
							<img class="rounded-3" src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
						</div>
						<div class="col-md-7 mt-3 mt-md-0">
							<a href="#" class="badge text-bg-danger mb-2"><i class="fas fa-circle me-2 small fw-bold"></i>{{ post.category}}</a>
							<h4><a href="{{post.get_absolute_url}}" class="btn-link stretched-link text-reset">{{ post.title}}</a></h4>
							<p>{{ post.description | markdown | truncatewords:40 }} </p>
							<!-- Card info -->
							<ul class="nav nav-divider align-items-center d-none d-sm-inline-block">
								<li class="nav-item">
									<div class="nav-link">
										<div class="d-flex align-items-center position-relative">
											<div class="avatar avatar-xs">
												<img class="avatar-img rounded-circle" src="{{ post.author.account.photo.url }}" alt="avatar">
											</div>
											<span class="ms-3">توسط <a href="#" class="stretched-link text-reset btn-link">{{ post.author }}</a></span>
										</div>
									</div>
								</li>
								<li class="nav-item">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</li>
							</ul>
						</div>
					</div>
				</div>
                {% endfor %}
				<!-- Card item END -->

			</div>
			<!-- Main Post END -->

			<!-- Sidebar START -->
			<div class="col-lg-3 mt-5 mt-lg-0">
				<div data-sticky data-margin-top="80" data-sticky-for="767">
					<!-- Trending topics widget START -->
					<div>
						<h4 class="mb-3">دسته بندی</h4>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url("#"); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog1:post_list_category' 'تکنولوژِی' %}" class="stretched-link btn-link text-white h5">تکنولوژِی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/02.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog1:post_list_category' 'هوش مصنوعی' %}" class="stretched-link btn-link text-white h5">هوش مصنوعی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog/4by3/03.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog1:post_list_category' 'زبان برنامه نویسی' %}" class="stretched-link btn-link text-white h5">زبان برنامه نویسی</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog1/4by3/04.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog1:post_list_category' 'بلاکچین' %}" class="stretched-link btn-link text-white h5">بلاکچین</a>
							</div>
						</div>
						<!-- Category item -->
						<div class="text-center mb-3 card-bg-scale position-relative overflow-hidden rounded" style="background-image:url(assets/images/blog1/4by3/05.jpg); background-position: center left; background-size: cover;">
							<div class="bg-dark-overlay-4 p-3">
								<a href="{% url 'blog1:post_list_category' 'سایر' %}" class="stretched-link btn-link text-white h5">سایر</a>
							</div>
						</div>
						<!-- View All Category button -->
						<div class="text-center mt-3">
							<a href="{% url 'blog1:post_list' %}" class="text-muted text-primary-hover"><u>مشاهده همه</u></a>
						</div>
					</div>
					<!-- Trending topics widget END -->

					<div class="row">
						<!-- Recent post widget START -->
						<div class="col-12 col-sm-6 col-lg-12">
							<h4 class="mt-4 mb-3">پربحث ترین ها</h4>
							<!--  post item -->
                            {% most_popular_posts 5 as pop_posts %}
                            {% for post in pop_posts %}
							<div class="card mb-3">
								<div class="row g-3">
									<div class="col-4">
										<img class="rounded" src="{{ post.images.first.image_field.url}}" alt="">
									</div>
									<div class="col-8">
										<h6><a href="{{post.get_absolute_url}}" class="btn-link stretched-link text-reset">{{post.title}}</a></h6>
										<div class="small mt-1">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</div>
									</div>
								</div>
							</div>
                            {% endfor %}
						</div>
						<!--  post widget END -->

					</div>
				</div>
			</div>
			<!-- Sidebar END -->
		</div> <!-- Row end -->
	</div>
</section>
</main>

	<div class="back-top"><i class="bi bi-arrow-up-short"></i></div>
    <script src="{% static 'vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
	<script src="{% static 'vendor/sticky-js/sticky.min.js' %}"></script>
	<script src="{% static 'js/functions.js' %}"></script>
{#    {% include "partials/pagination.html" with page=page_obj%}#}
    {% include "partilas/pagination.html" with page=posts%}
{% endblock %}

blog1/templates/blog1/profile.html
{% extends 'parent/basa.html' %}
{% block title %}profile{% endblock %}
{% block content %}
    <p><a href="{% url 'blog1:create_post' %}">ایجاد پست جدید</a></p>
<table style="width: 100%; border: 3px solid brown ; text-align : right ; direction: rtl">
    <tr>
        <th>ردیف</th>
        <th>پست</th>
        <th>مشاهده</th>
        <th>ویرایش</th>
        <th>حذف</th>
    </tr>
    {% for post in posts %}
    <tr>
        <td>{{ forloop.counter}}</td>
        <td>{{ post.title}}</td>
        <td><a href="{{ post.get_absolute_url }}">{{ post.title}}</a></td>
        <td><a href="{% url 'blog1:edit_post' post.id %}">ویرایش</a></td>
        <td><a href="{% url 'blog1:delete_post' post.id %}">حذف</a></td>
    </tr>
    {% endfor %}
    </table>
        <br>
        <a href="{% url 'blog1:password_change' %}">تغییر پسورد</a>
        <br>
        <a href="{% url 'blog1:logout' %}">خروج</a>
        <br>
{% endblock %}

blog1/templates/blog1/search.html
{% extends 'parent/basa.html' %}
{% block title %} post search {% endblock %}
{% block content %}
    {% if query %}
        {{ results.count }} نتایج جستجو برای: {{ query }}
    {% endif %}
    <br>
    {% for post in results %}
        <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
        <p>{{ post.description }}</p>
    {% empty %}
        هیچ نتیجه ای یافت نشد!
    {% endfor %}
{% endblock %}